# Generated by Django 2.2.2 on 2019-06-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=14)),
                ('signed_up', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=14)),
                ('signed_up', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='special_second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bio', models.CharField(max_length=500)),
                ('activities', models.CharField(choices=[('DNC', 'Dancing'), ('SNG', 'Singing'), ('SWM', 'Swimming'), ('PLN', 'Playing'), ('CLC', 'Cycling'), ('COG', 'Cognition')], max_length=3)),
                ('disability', models.CharField(choices=[('APD', 'Audiotory Processing Disorder'), ('DYC', 'Dyscalculia'), ('DYG', 'Dysgraphia'), ('DYS', 'Dyslexia'), ('LPD', 'Language Processing Disorder'), ('NLD', 'Non Verbal Learning Disabilities'), ('VMD', 'Visual Perceptual Motor Deficit'), ('ADD', 'Attention Deficient Hyperactivity Disorder'), ('DYP', 'Dyspraxia'), ('EXF', 'Executive Functioning'), ('MEM', 'Memory')], max_length=3)),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flap.special')),
            ],
        ),
        migrations.CreateModel(
            name='organization_second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('maximum_age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('info', models.CharField(max_length=500)),
                ('activities', models.CharField(choices=[('DNC', 'Dancing'), ('SNG', 'Singing'), ('SWM', 'Swimming'), ('PLN', 'Playing'), ('CLC', 'Cycling'), ('COG', 'Cognition')], max_length=3)),
                ('disability', models.CharField(choices=[('APD', 'Audiotory Processing Disorder'), ('DYC', 'Dyscalculia'), ('DYG', 'Dysgraphia'), ('DYS', 'Dyslexia'), ('LPD', 'Language Processing Disorder'), ('NLD', 'Non Verbal Learning Disabilities'), ('VMD', 'Visual Perceptual Motor Deficit'), ('ADD', 'Attention Deficient Hyperactivity Disorder'), ('DYP', 'Dyspraxia'), ('EXF', 'Executive Functioning'), ('MEM', 'Memory')], max_length=3)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flap.organization')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('after_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('info', models.CharField(max_length=500)),
                ('activated', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flap.organization')),
            ],
        ),
        migrations.CreateModel(
            name='activation_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50)),
                ('mobile_key', models.CharField(max_length=5)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flap.organization')),
                ('special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flap.special')),
            ],
        ),
    ]
