# Generated by Django 2.2.2 on 2019-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_on',
        ),
        migrations.AddField(
            model_name='events',
            name='after_days',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=4),
            preserve_default=False,
        ),
    ]
